### ISSUE TITLE
favicon 404啦

### ISSUE THREAD

**Issue by greenmoon55** [hustlzp/xichuangzhu#15]
http://www.xichuangzhu.com/static/img/favicon.png

**Comment by hustlzp** [comment]
favicon的地址应该是：http://www.xichuangzhu.com/static/img/favicon_0fe6604.png

加了版本号的。

请问你是在哪里复制的链接？

**Comment by greenmoon55** [comment]
在“一首”里面，每首诗的最后面 http://classic.xichuangzhu.com/

**Comment by greenmoon55** [comment]
![image](https://cloud.githubusercontent.com/assets/1228142/11765074/f97f9d00-a183-11e5-9e8d-25927eea3956.png)

**Comment by hustlzp** [comment]
多谢提醒，已经好了。

一首的repo在这里：

https://github.com/xichuangzhu/xichuangzhu-classic
